mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
clash-for-android:
  append-system-dns: false
experimental:
  sniff-tls-sni: true
profile:
  tracing: true
dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: true
  enhanced-mode: fake-ip
  default-nameserver:
    - 101.198.198.198
    - 101.198.199.200
    - 52.80.66.66
    - 117.50.22.22
  nameserver:
    - 180.184.1.1
    - tcp://119.28.28.28
    - tls://dns.alidns.com:853
    - https://doh.pub/dns-query
  fallback:
    - https://1.0.0.1/dns-query
    - https://dns.sb/dns-query
    - https://dns.opendns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - stun.*.*
    - stun.*.*.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.nintendo.net
    - +.playstation.net
    - xbox.*.microsoft.com
    - xbox.*.*.microsoft.com
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - +.private
    - +.localdomain
    - +.home
    - +.host
    - +.home.arpa
    - +.test
    - +.example
    - +.invalid
    - +.localhost
    - +.local
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.xboxlive.com
    - +.ipv6.microsoft.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - heartbeat.belkin.com
    - +.linksys.com
    - +.linksyssmartwifi.com
    - +.router.asus.com
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - +.square-enix.com
    - +.finalfantasyxiv.com
    - +.ffxiv.com
    - +.sdo.com
    - +.media.dssott.com
    - +.pvp.net
    - +.nexon.co.jp
    - +.nexon.co.kr
    - +.nexon.com