mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
clash-for-android:
  append-system-dns: false
experimental:
  sniff-tls-sni: true
profile:
  tracing: true
dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: true
  use-hosts: true
  use-system-hosts: true
  enhanced-mode: fake-ip
  default-nameserver:
    - 101.198.198.198
    - 101.198.199.200
    - 114.114.114.114
    - 114.114.115.115
  nameserver-policy:
    'geosite:cn':
      - tls://dot.pub
      - https://9999.alidns.com/dns-query
  nameserver:
    - tls://dot.pub
    - https://9999.alidns.com/dns-query
  fallback:
    - tls://p0.freedns.controld.com
    - https://doh.harusaruhi.lol/dns-query
  proxy-server-nameserver:
    - tls://dot.pub
    - https://9999.alidns.com/dns-query
  direct-nameserver:
    - tls://dot.pub
    - https://9999.alidns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  fake-ip-filter:
    - "*.lan"
    - "*.teafone.com"
    - "*.sktswe.net"
    - rtc.goodfone.co.kr
    - "*.chattti.com"
    - localhost.ptlogin2.qq.com
    - stun.*.*
    - stun.*.*.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.nintendo.net
    - +.playstation.net
    - xbox.*.microsoft.com
    - xbox.*.*.microsoft.com
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - +.ntp.org
    - ntp.ubuntu.com
    - ntp.aliyun.com
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
    - "*.time.edu.cn"
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - +.private
    - +.localdomain
    - +.home
    - +.host
    - +.home.arpa
    - +.test
    - +.example
    - +.invalid
    - +.localhost
    - +.local
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.xboxlive.com
    - +.ipv6.microsoft.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - heartbeat.belkin.com
    - +.linksys.com
    - +.linksyssmartwifi.com
    - +.router.asus.com
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - +.square-enix.com
    - +.finalfantasyxiv.com
    - +.ffxiv.com
    - +.sdo.com
    - +.media.dssott.com
    - +.pvp.net