mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true

experimental:
  sniff-tls-sni: true

dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: true
  default-nameserver:
    - 101.198.198.198
    - 101.198.199.200
    - 101.226.4.6
    - 123.125.81.6
    - 218.30.118.6
    - 140.207.198.6
  nameserver:
    - 180.184.1.1
    - tls://dns.pub:853
    - https://dns.alidns.com/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - '*.n.n.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
    - '+.private'
    - '+.localdomain'
    - '+.home'
    - '+.host'
    - '+.home.arpa'
    - '+.test'
    - '+.example'
    - '+.invalid'
    - '+.localhost'
    - '+.local'
    - +.msftconnecttest.com
    - +.msftncsi.com
    - msftconnecttest.com
    - msftncsi.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - +.ipv6.microsoft.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - heartbeat.belkin.com
    - +.linksys.com
    - +.linksyssmartwifi.com
    - +.router.asus.com
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - +.square-enix.com
    - +.finalfantasyxiv.com
    - +.ffxiv.com
    - +.ff14.sdo.com
    - ff.dorado.sdo.com
    - +.media.dssott.com
    - +.pvp.net
    - +.nexon.co.jp
    - +.nexon.co.kr
    - +.nexon.com