mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false

experimental:
  sniff-tls-sni: true

dns:
  enable: true
  listen: 127.0.0.1:5353
  ipv6: false
  default-nameserver:
    - 180.184.1.1
    - 52.80.52.52
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - '*.n.n.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
    - '+.private'
    - '+.localdomain'
    - '+.home'
    - '+.host'
    - '+.home.arpa'
    - '+.test'
  nameserver:
    - tls://223.5.5.5:853
    - https://1.12.12.12/dns-query
  fallback:
    - tls://dns.opendns.com:853
    - https://doh.dns.sb/dns-query
  fallback-filter:
    geoip: false
    # geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.g.cn
      - +.google.cn
      - +.googleapis.cn
      - +.google.com
      - +.googleapis.com
      - +.gmail.com
      - +.youtube.com
      - +.youtu.be
      - +.googlevideo.com
      - +.doubleclick.net
      - +.akamai.net
      - +.akamaized.net

# Clash for Windows
# cfw-latency-timeout: 3000
# cfw-latency-url: http://cp.cloudflare.com/generate_204
# cfw-conn-break-strategy:
#   proxy: all
#   profile: true
#   mode: true
